package cli

import (
	"fmt"
	"html/template"
	"os"
	"time"
)

// ReportData holds all data passed to the HTML report template.
type ReportData struct {
	Owner        string
	ConfigPath   string
	Branch       string
	GeneratedAt  string
	Results      []RepoAuditResult
	Compliant    int
	NonCompliant int
	Skipped      int
	Total        int
}

const reportTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Rampart Audit Report — {{.Owner}}</title>
<style>
  *, *::before, *::after { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: #f6f8fa; color: #24292f; margin: 0; padding: 2rem;
  }
  h1 { margin: 0 0 0.25rem; }
  .meta { color: #57606a; font-size: 0.9rem; margin-bottom: 1.5rem; }
  .summary {
    display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 2rem;
  }
  .summary .stat {
    background: #fff; border: 1px solid #d0d7de; border-radius: 8px;
    padding: 1rem 1.5rem; min-width: 140px; text-align: center;
  }
  .stat .num { font-size: 2rem; font-weight: 700; }
  .stat .label { font-size: 0.85rem; color: #57606a; text-transform: uppercase; }
  .stat.compliant .num { color: #1a7f37; }
  .stat.non-compliant .num { color: #cf222e; }
  .stat.skipped .num { color: #6e7781; }
  .stat.total .num { color: #0969da; }
  .card {
    background: #fff; border: 1px solid #d0d7de; border-radius: 8px;
    margin-bottom: 1rem; border-left: 4px solid #d0d7de; overflow: hidden;
  }
  .card.pass { border-left-color: #1a7f37; }
  .card.fail { border-left-color: #cf222e; }
  .card.skip { border-left-color: #6e7781; }
  .card-header {
    padding: 0.75rem 1rem; font-weight: 600; font-size: 1rem;
    display: flex; align-items: center; gap: 0.5rem;
  }
  .badge {
    font-size: 0.75rem; font-weight: 600; padding: 0.15rem 0.5rem;
    border-radius: 999px; color: #fff;
  }
  .badge.pass { background: #1a7f37; }
  .badge.fail { background: #cf222e; }
  .badge.skip { background: #6e7781; }
  .card-body { padding: 0 1rem 0.75rem; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  th { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 2px solid #d0d7de; color: #57606a; }
  td { padding: 0.4rem 0.6rem; border-bottom: 1px solid #eaeef2; }
  tr.rule-pass td:first-child::before { content: "✓ "; color: #1a7f37; }
  tr.rule-fail td:first-child::before { content: "✗ "; color: #cf222e; }
  tr.rule-fail { background: #fff5f5; }
  footer {
    margin-top: 2rem; text-align: center; color: #6e7781; font-size: 0.8rem;
  }
</style>
</head>
<body>
<h1>Rampart Audit Report</h1>
<p class="meta">Owner: <strong>{{.Owner}}</strong> · Config: <strong>{{.ConfigPath}}</strong> · Branch: <strong>{{.Branch}}</strong></p>

<div class="summary">
  <div class="stat total"><div class="num">{{.Total}}</div><div class="label">Total</div></div>
  <div class="stat compliant"><div class="num">{{.Compliant}}</div><div class="label">Compliant</div></div>
  <div class="stat non-compliant"><div class="num">{{.NonCompliant}}</div><div class="label">Non-Compliant</div></div>
  <div class="stat skipped"><div class="num">{{.Skipped}}</div><div class="label">Skipped</div></div>
</div>

{{range .Results}}
<div class="card {{if .Skipped}}skip{{else if .Compliant}}pass{{else}}fail{{end}}">
  <div class="card-header">
    {{.Repo}}
    {{if .Skipped}}<span class="badge skip">SKIPPED</span>
    {{else if .Compliant}}<span class="badge pass">PASS</span>
    {{else}}<span class="badge fail">FAIL</span>
    {{end}}
    {{if and .Branch (not .Skipped)}}<span style="font-weight:normal;color:#57606a;font-size:0.85rem">({{.Branch}})</span>{{end}}
  </div>
  {{if .Error}}<div class="card-body" style="color:#57606a">{{.Error}}</div>{{end}}
  {{if and (not .Compliant) (not .Skipped) .Diffs}}
  <div class="card-body">
    <table>
      <tr><th>Rule</th><th>Expected</th><th>Actual</th><th>Status</th></tr>
      {{range .Diffs}}
      <tr class="{{if .Pass}}rule-pass{{else}}rule-fail{{end}}">
        <td>{{.Rule}}</td><td>{{.Want}}</td><td>{{.Got}}</td>
        <td>{{if .Pass}}Pass{{else}}Fail{{end}}</td>
      </tr>
      {{end}}
    </table>
  </div>
  {{end}}
</div>
{{end}}

<footer>Generated by rampart · {{.GeneratedAt}}</footer>
</body>
</html>
`

func generateReport(path string, data ReportData) error {
	tmpl, err := template.New("report").Parse(reportTemplate)
	if err != nil {
		return fmt.Errorf("parsing report template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating report file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("executing report template: %w", err)
	}
	return nil
}

func newReportData(owner, configPath, branch string, results []RepoAuditResult) ReportData {
	data := ReportData{
		Owner:       owner,
		ConfigPath:  configPath,
		Branch:      branch,
		GeneratedAt: time.Now().Format("2006-01-02 15:04:05 MST"),
		Results:     results,
		Total:       len(results),
	}
	for _, r := range results {
		switch {
		case r.Skipped:
			data.Skipped++
		case r.Error != "" || !r.Compliant:
			data.NonCompliant++
		default:
			data.Compliant++
		}
	}
	return data
}
